# Generated by Django 4.0.3 on 2022-04-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_comment_is_active_comment_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
