# Generated by Django 4.0.3 on 2022-04-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_comment_email_comment_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='fullname',
        ),
    ]
